// client/src/game/content/dummyQuestions.ts
//
// [担当: task_content] ダミー問題データ。
// 国語・算数・英語 × 小2/小5 の組み合わせごとに最低5問を用意すること
// (3科目 × 2学年 = 6区分 × 最低5問 = 最低30問)。
// 実装ガイドは実装計画JSONの task_content.instructions を参照。
// 現時点では空配列のスタブ。

import type { ContentItem } from "@/game/types";

export const DUMMY_QUESTIONS: ContentItem[] = [
  // ==================== 国語/小2 ====================
  {
    id: "japanese-grade2-1",
    subject: "japanese",
    grade: "grade2",
    unit: "説明文の要点",
    prompt: "ねこは夜に目がよく見えます。ねこの目は、少しの光でも反射して光ります。",
    choices: [
      { id: "a", label: "ねこは昼間に目がよい" },
      { id: "b", label: "ねこは夜に目がよく見える" },
      { id: "c", label: "ねこは耳がよい" },
    ],
    correctChoiceId: "b",
    explanation: "文章の最初の文が『ねこは夜に目がよく見えます』と説明しています。",
    difficulty: 1,
  },
  {
    id: "japanese-grade2-2",
    subject: "japanese",
    grade: "grade2",
    unit: "登場人物の気持ち",
    prompt:
      "太郎は試験に合格しました。家に帰ると、お母さんが『よくがんばったね』と笑いながら言いました。",
    choices: [
      { id: "a", label: "太郎は悲しい気持ち" },
      { id: "b", label: "太郎は嬉しい気持ち" },
      { id: "c", label: "太郎は怖い気持ち" },
    ],
    correctChoiceId: "b",
    explanation: "試験に合格して、お母さんにほめられたので、太郎は嬉しい気持ちです。",
    difficulty: 1,
  },
  {
    id: "japanese-grade2-3",
    subject: "japanese",
    grade: "grade2",
    unit: "説明文の要点",
    prompt:
      "バナナはいつ実がなるのでしょう。バナナの木は温かい国で育ちます。温かい場所なら、一年中実がなります。",
    choices: [
      { id: "a", label: "バナナは冬だけ実がなる" },
      { id: "b", label: "バナナは寒い国で育つ" },
      { id: "c", label: "温かい場所なら、バナナは一年中実がなる" },
    ],
    correctChoiceId: "c",
    explanation: "文章に『温かい場所なら、一年中実がなります』と書いてあります。",
    difficulty: 2,
  },
  {
    id: "japanese-grade2-4",
    subject: "japanese",
    grade: "grade2",
    unit: "登場人物の気持ち",
    prompt:
      "花子は絵の大会に出すために、毎日絵を描きました。今日、結果が届きました。『優秀賞』と書いてありました。",
    choices: [
      { id: "a", label: "頑張った成果が出て嬉しい" },
      { id: "b", label: "絵を描くのは楽しくない" },
      { id: "c", label: "大会に出たくなかった" },
    ],
    correctChoiceId: "a",
    explanation: "毎日頑張った花子が優秀賞を取ったので、成果が出て嬉しいはずです。",
    difficulty: 2,
  },
  {
    id: "japanese-grade2-5",
    subject: "japanese",
    grade: "grade2",
    unit: "説明文の要点",
    prompt:
      "トマトを育てるコツを知っていますか。毎日水をあげることが大事です。でも、土が乾いていないなら、水をあげてはいけません。",
    choices: [
      { id: "a", label: "毎日必ず水をあげる" },
      { id: "b", label: "土が乾いていない時も水をあげる" },
      { id: "c", label: "土が乾いていない時は水をあげない" },
    ],
    correctChoiceId: "c",
    explanation: "『土が乾いていないなら、水をあげてはいけません』と書いてあります。",
    difficulty: 2,
  },
  {
    id: "japanese-grade2-6",
    subject: "japanese",
    grade: "grade2",
    unit: "登場人物の気持ち",
    prompt:
      "学校の運動会で、次郎は100メートル走に出ました。走り終わった後、次郎は息を切らせながら『僕は1番になれなかった』と言いました。でも、先生は『最後まで一生懸命走ったね』とほめました。",
    choices: [
      { id: "a", label: "次郎は悔しいけど、頑張ったことが嬉しい" },
      { id: "b", label: "次郎は走るのが嫌だ" },
      { id: "c", label: "次郎は1番じゃないから、何も学んでいない" },
    ],
    correctChoiceId: "a",
    explanation: "1番になれず悔しいけれど、先生にほめられて頑張ったことの大切さを感じています。",
    difficulty: 3,
  },

  // ==================== 国語/小5 ====================
  {
    id: "japanese-grade5-1",
    subject: "japanese",
    grade: "grade5",
    unit: "説明的文章の要点",
    prompt:
      "インターネットは世界中の情報を瞬間にして手に入れることができる便利な道具です。しかし、正しくない情報も多くあります。ですから、得た情報が正しいか確認することが大切です。",
    choices: [
      { id: "a", label: "インターネットの情報はすべて正しい" },
      { id: "b", label: "インターネットは不便な道具である" },
      { id: "c", label: "インターネットの情報は正しいかどうか確認が必要" },
    ],
    correctChoiceId: "c",
    explanation:
      "文章は『得た情報が正しいか確認することが大切です』と結論づけています。",
    difficulty: 1,
  },
  {
    id: "japanese-grade5-2",
    subject: "japanese",
    grade: "grade5",
    unit: "漢字の読み書き",
    prompt:
      "次の文で「夏の日中は気温が上昇する」の「上昇」と同じ意味の漢字2字を選んでください。",
    choices: [
      { id: "a", label: "下降" },
      { id: "b", label: "増加" },
      { id: "c", label: "減少" },
      { id: "d", label: "上昇" },
    ],
    correctChoiceId: "d",
    explanation:
      "「上昇」は数値や量が高くなることを意味します。「増加」も似た意味ですが、この文脈では「上昇」が最も適切です。",
    difficulty: 2,
  },
  {
    id: "japanese-grade5-3",
    subject: "japanese",
    grade: "grade5",
    unit: "説明的文章の要点",
    prompt:
      "動物には、冬に食べ物が少なくなるのに備えて、体に脂肪を蓄える種類がいます。これを『冬眠の準備』と言います。冬眠する動物は、秋にたくさん食べて、冬は寝たままエネルギーを使わないようにします。",
    choices: [
      { id: "a", label: "冬眠する動物は冬に活発に活動する" },
      { id: "b", label: "冬眠の準備とは、秋に脂肪を蓄えて冬に少ないエネルギーで生きること" },
      { id: "c", label: "すべての動物が冬眠する" },
    ],
    correctChoiceId: "b",
    explanation:
      "文章に『秋にたくさん食べて、冬は寝たままエネルギーを使わないようにします』と説明されています。",
    difficulty: 2,
  },
  {
    id: "japanese-grade5-4",
    subject: "japanese",
    grade: "grade5",
    unit: "物語文の読解",
    prompt:
      "美咲は学校の図書館で、昔の日本の暮らしについて調べていました。担当の先生は『この本は参考になるよ』と勧めてくれました。美咲は『本当ですか。ありがとうございます』と礼を言いました。",
    choices: [
      { id: "a", label: "美咲は先生からもらった本に感謝している" },
      { id: "b", label: "美咲は調べる気がない" },
      { id: "c", label: "美咲は図書館が嫌いだ" },
    ],
    correctChoiceId: "a",
    explanation:
      "『ありがとうございます』と礼を言ったことから、美咲が先生の親切に感謝していることがわかります。",
    difficulty: 1,
  },
  {
    id: "japanese-grade5-5",
    subject: "japanese",
    grade: "grade5",
    unit: "説明的文章の要点",
    prompt:
      "太陽光発電とは、太陽の光をエネルギーに変える技術です。これにより、電気を作ることができます。太陽光発電は環境を汚さないため、今後ますます使われるようになると考えられています。",
    choices: [
      { id: "a", label: "太陽光発電は環境を汚す" },
      { id: "b", label: "太陽光発電は、太陽の光を電気に変える環境に優しい技術" },
      { id: "c", label: "太陽光発電は現在使われていない" },
    ],
    correctChoiceId: "b",
    explanation:
      "文章は『太陽の光をエネルギーに変える技術』で『環境を汚さない』と説明しています。",
    difficulty: 2,
  },
  {
    id: "japanese-grade5-6",
    subject: "japanese",
    grade: "grade5",
    unit: "物語文の読解",
    prompt:
      "健太は毎日部屋を汚したままにしていました。ある日、お母さんが『健太へ』と手紙を置きました。手紙には『自分の部屋は自分で整理整頓することが、大人になるための第一歩だと思います。頑張ってね』と書いてありました。読んだ健太は『ぼくも頑張ろう』と思い、その日から部屋を整理し始めました。",
    choices: [
      { id: "a", label: "健太はお母さんが部屋を整理することを嫌だと思った" },
      { id: "b", label: "お母さんの手紙を読んで、健太の気持ちが変わった" },
      { id: "c", label: "健太は大人になりたくないと思っている" },
    ],
    correctChoiceId: "b",
    explanation:
      "手紙を読んだ後に『ぼくも頑張ろう』と思い、行動を変えたので、健太の気持ちが変わったことがわかります。",
    difficulty: 3,
  },

  // ==================== 算数/小2 ====================
  {
    id: "math-grade2-1",
    subject: "math",
    grade: "grade2",
    unit: "たし算の筆算",
    prompt: "23 + 15 の計算を筆算で行います。答えはいくつですか。",
    choices: [
      { id: "a", label: "28" },
      { id: "b", label: "38" },
      { id: "c", label: "48" },
    ],
    correctChoiceId: "b",
    explanation: "23 + 15 = 38 です。一の位 3 + 5 = 8、十の位 2 + 1 = 3 なので答えは38です。",
    difficulty: 1,
  },
  {
    id: "math-grade2-2",
    subject: "math",
    grade: "grade2",
    unit: "ひき算の筆算",
    prompt: "35 - 12 の計算を筆算で行います。答えはいくつですか。",
    choices: [
      { id: "a", label: "13" },
      { id: "b", label: "23" },
      { id: "c", label: "33" },
    ],
    correctChoiceId: "b",
    explanation: "35 - 12 = 23 です。一の位 5 - 2 = 3、十の位 3 - 1 = 2 なので答えは23です。",
    difficulty: 1,
  },
  {
    id: "math-grade2-3",
    subject: "math",
    grade: "grade2",
    unit: "長さの単位",
    prompt: "消しゴムの長さは約何センチメートルですか。",
    choices: [
      { id: "a", label: "1 cm" },
      { id: "b", label: "5 cm" },
      { id: "c", label: "20 cm" },
    ],
    correctChoiceId: "b",
    explanation: "一般的な消しゴムの長さは約5センチメートルです。",
    difficulty: 1,
  },
  {
    id: "math-grade2-4",
    subject: "math",
    grade: "grade2",
    unit: "たし算の筆算",
    prompt: "お店で鉛筆を24本買いました。帰り道で友達に13本あげました。手元に残っている鉛筆は何本ですか。",
    choices: [
      { id: "a", label: "11本" },
      { id: "b", label: "37本" },
      { id: "c", label: "10本" },
    ],
    correctChoiceId: "a",
    explanation: "24 - 13 = 11 です。一の位 4 - 3 = 1、十の位 2 - 1 = 1 なので答えは11本です。",
    difficulty: 2,
  },
  {
    id: "math-grade2-5",
    subject: "math",
    grade: "grade2",
    unit: "ひき算の筆算",
    prompt: "52 - 28 の計算を筆算で行います。答えはいくつですか。",
    choices: [
      { id: "a", label: "24" },
      { id: "b", label: "34" },
      { id: "c", label: "80" },
    ],
    correctChoiceId: "a",
    explanation:
      "52 - 28 = 24 です。一の位では 2 - 8 ができないので、十の位から1を借りて、12 - 8 = 4。十の位は借りた分を引いて、4 - 2 = 2 なので答えは24です。",
    difficulty: 2,
  },
  {
    id: "math-grade2-6",
    subject: "math",
    grade: "grade2",
    unit: "長さの単位",
    prompt: "教室の廊下の長さは何メートルですか。最も近い答えを選んでください。",
    choices: [
      { id: "a", label: "5メートル" },
      { id: "b", label: "50センチメートル" },
      { id: "c", label: "300メートル" },
    ],
    correctChoiceId: "a",
    explanation: "一般的な小学校の廊下は5メートル程度です。50 cm は短すぎ、300 m は長すぎます。",
    difficulty: 2,
  },

  // ==================== 算数/小5 ====================
  {
    id: "math-grade5-1",
    subject: "math",
    grade: "grade5",
    unit: "分数のたし算",
    prompt: "1/3 + 1/3 の計算をしてください。答えはいくつですか。",
    choices: [
      { id: "a", label: "1/6" },
      { id: "b", label: "2/3" },
      { id: "c", label: "2/6" },
    ],
    correctChoiceId: "b",
    explanation: "分母が同じ分数のたし算は、分子を足します。1 + 1 = 2 なので答えは 2/3 です。",
    difficulty: 1,
  },
  {
    id: "math-grade5-2",
    subject: "math",
    grade: "grade5",
    unit: "割合",
    prompt: "全体が100個の商品のうち、20個が売れました。売れた商品は全体の何パーセントですか。",
    choices: [
      { id: "a", label: "10%" },
      { id: "b", label: "20%" },
      { id: "c", label: "30%" },
    ],
    correctChoiceId: "b",
    explanation: "20 ÷ 100 × 100 = 20% です。",
    difficulty: 1,
  },
  {
    id: "math-grade5-3",
    subject: "math",
    grade: "grade5",
    unit: "図形の面積",
    prompt: "たて4 cm、横6 cm の長方形の面積は何平方センチメートルですか。",
    choices: [
      { id: "a", label: "10 cm²" },
      { id: "b", label: "20 cm²" },
      { id: "c", label: "24 cm²" },
    ],
    correctChoiceId: "c",
    explanation: "長方形の面積 = たて × 横 = 4 × 6 = 24 cm² です。",
    difficulty: 1,
  },
  {
    id: "math-grade5-4",
    subject: "math",
    grade: "grade5",
    unit: "分数のたし算",
    prompt: "1/2 + 1/4 の計算をしてください。答えはいくつですか。",
    choices: [
      { id: "a", label: "2/6" },
      { id: "b", label: "3/4" },
      { id: "c", label: "1/4" },
    ],
    correctChoiceId: "b",
    explanation:
      "分母を4に統一します。1/2 = 2/4 なので、2/4 + 1/4 = 3/4 です。",
    difficulty: 2,
  },
  {
    id: "math-grade5-5",
    subject: "math",
    grade: "grade5",
    unit: "割合",
    prompt: "太郎君は1000円を持っていました。本に400円を使いました。残ったお金は全体の何パーセントですか。",
    choices: [
      { id: "a", label: "40%" },
      { id: "b", label: "60%" },
      { id: "c", label: "400%" },
    ],
    correctChoiceId: "b",
    explanation:
      "残ったお金は 1000 - 400 = 600 円です。割合は 600 ÷ 1000 × 100 = 60% です。",
    difficulty: 2,
  },
  {
    id: "math-grade5-6",
    subject: "math",
    grade: "grade5",
    unit: "図形の面積",
    prompt: "平行四辺形の底辺が8 cm、高さが5 cm です。面積は何平方センチメートルですか。",
    choices: [
      { id: "a", label: "13 cm²" },
      { id: "b", label: "26 cm²" },
      { id: "c", label: "40 cm²" },
    ],
    correctChoiceId: "c",
    explanation: "平行四辺形の面積 = 底辺 × 高さ = 8 × 5 = 40 cm² です。",
    difficulty: 2,
  },

  // ==================== 英語/小2 ====================
  {
    id: "english-grade2-1",
    subject: "english",
    grade: "grade2",
    unit: "あいさつ表現",
    prompt: "朝、友達に会った時、何と言いますか。",
    choices: [
      { id: "a", label: "Good morning." },
      { id: "b", label: "Good night." },
      { id: "c", label: "Goodbye." },
    ],
    correctChoiceId: "a",
    explanation: "朝のあいさつは 'Good morning.' です。'Good night.' は夜寝る前です。",
    difficulty: 1,
  },
  {
    id: "english-grade2-2",
    subject: "english",
    grade: "grade2",
    unit: "動物の単語",
    prompt: "この動物は何ですか。(ニャーニャーと鳴く)",
    choices: [
      { id: "a", label: "cat" },
      { id: "b", label: "dog" },
      { id: "c", label: "bird" },
    ],
    correctChoiceId: "a",
    explanation: "'cat' は猫を意味します。ニャーニャーと鳴くのは猫です。",
    difficulty: 1,
  },
  {
    id: "english-grade2-3",
    subject: "english",
    grade: "grade2",
    unit: "あいさつ表現",
    prompt: "友達が帰る時、何と言いますか。",
    choices: [
      { id: "a", label: "Hello." },
      { id: "b", label: "Goodbye." },
      { id: "c", label: "How are you?" },
    ],
    correctChoiceId: "b",
    explanation: "'Goodbye.' は別れる時のあいさつです。",
    difficulty: 1,
  },
  {
    id: "english-grade2-4",
    subject: "english",
    grade: "grade2",
    unit: "動物の単語",
    prompt: "この動物は何ですか。(ワンワンと鳴く)",
    choices: [
      { id: "a", label: "dog" },
      { id: "b", label: "cat" },
      { id: "c", label: "pig" },
    ],
    correctChoiceId: "a",
    explanation: "'dog' は犬を意味します。ワンワンと鳴くのは犬です。",
    difficulty: 1,
  },
  {
    id: "english-grade2-5",
    subject: "english",
    grade: "grade2",
    unit: "あいさつ表現",
    prompt: "相手の元気を聞く時、何と言いますか。",
    choices: [
      { id: "a", label: "What is your name?" },
      { id: "b", label: "How are you?" },
      { id: "c", label: "Where are you?" },
    ],
    correctChoiceId: "b",
    explanation: "'How are you?' は相手の元気や調子を聞く表現です。",
    difficulty: 1,
  },
  {
    id: "english-grade2-6",
    subject: "english",
    grade: "grade2",
    unit: "動物の単語",
    prompt: "この動物は何ですか。(羽があって、空を飛ぶ)",
    choices: [
      { id: "a", label: "fish" },
      { id: "b", label: "bird" },
      { id: "c", label: "rabbit" },
    ],
    correctChoiceId: "b",
    explanation: "'bird' は鳥を意味します。羽があり空を飛びます。",
    difficulty: 2,
  },

  // ==================== 英語/小5 ====================
  {
    id: "english-grade5-1",
    subject: "english",
    grade: "grade5",
    unit: "曜日・時刻の表現",
    prompt: "1週間の1番目の日は何ですか。",
    choices: [
      { id: "a", label: "Monday" },
      { id: "b", label: "Sunday" },
      { id: "c", label: "Saturday" },
    ],
    correctChoiceId: "b",
    explanation: "Sunday（日曜日）が1週間の最初の日です。",
    difficulty: 1,
  },
  {
    id: "english-grade5-2",
    subject: "english",
    grade: "grade5",
    unit: "身近な単語の綴り",
    prompt: "この単語のつづりは何ですか。(季節：あき)",
    choices: [
      { id: "a", label: "autumn" },
      { id: "b", label: "summer" },
      { id: "c", label: "spring" },
    ],
    correctChoiceId: "a",
    explanation: "'autumn' は秋を意味する英単語です。",
    difficulty: 1,
  },
  {
    id: "english-grade5-3",
    subject: "english",
    grade: "grade5",
    unit: "曜日・時刻の表現",
    prompt: "午後2時を英語で何と言いますか。",
    choices: [
      { id: "a", label: "2:00 AM" },
      { id: "b", label: "2:00 PM" },
      { id: "c", label: "14:00 AM" },
    ],
    correctChoiceId: "b",
    explanation: "午後は PM を使い、'2:00 PM' が午後2時を表します。",
    difficulty: 1,
  },
  {
    id: "english-grade5-4",
    subject: "english",
    grade: "grade5",
    unit: "身近な単語の綴り",
    prompt: "この単語のつづりは何ですか。(季節：冬)",
    choices: [
      { id: "a", label: "winter" },
      { id: "b", label: "autumn" },
      { id: "c", label: "fall" },
    ],
    correctChoiceId: "a",
    explanation: "'winter' は冬を意味する英単語です。",
    difficulty: 1,
  },
  {
    id: "english-grade5-5",
    subject: "english",
    grade: "grade5",
    unit: "曜日・時刻の表現",
    prompt: "火曜日の英語は何ですか。",
    choices: [
      { id: "a", label: "Tuesday" },
      { id: "b", label: "Thursday" },
      { id: "c", label: "Wednesday" },
    ],
    correctChoiceId: "a",
    explanation: "'Tuesday' が火曜日を表す英語です。",
    difficulty: 2,
  },
  {
    id: "english-grade5-6",
    subject: "english",
    grade: "grade5",
    unit: "身近な単語の綴り",
    prompt: "この単語のつづりは何ですか。(果物：リンゴ)",
    choices: [
      { id: "a", label: "apple" },
      { id: "b", label: "orange" },
      { id: "c", label: "banana" },
    ],
    correctChoiceId: "a",
    explanation: "'apple' はリンゴを意味する英単語です。",
    difficulty: 2,
  },
];
