// client/src/game/content/questions/english.ts
//
// 英語コンテンツ(小2は任意の早期導入・遊び感覚の内容、小5は外国語科の学習指導要領準拠)。
//
// 小2: 学習指導要領上、外国語活動は小3から、教科としての外国語科は小5からのため、
//      小2向けの英語コンテンツは必修内容ではない。あいさつ・色・数字・動物・食べ物・
//      体の部位など、遊び感覚で親しめる身近な単語・表現に限定し、難易度は易(1)中心とする。
// 小5: 外国語科(5・6年)の学習指導要領・教科書(We Can!, Let's Try 等)を参考に、
//      自己紹介/好き嫌い/曜日・時刻/教科名/日課/できること/道案内初歩/食べ物/天気/
//      数字/色/動物/家族の各トピックをカバーする。

import type { ContentItem } from "@/game/types";

export const ENGLISH_QUESTIONS: ContentItem[] = [
  // ==================== 英語/小2(学習指導要領上の必修外。早期導入・遊び感覚) ====================
  {
    id: "english-grade2-1",
    subject: "english",
    grade: "grade2",
    unit: "あいさつ表現",
    prompt: "朝、友達に会った時のあいさつはどれですか。",
    choices: [
      { id: "a", label: "Good night." },
      { id: "b", label: "Good morning." },
      { id: "c", label: "Goodbye." },
    ],
    correctChoiceId: "b",
    explanation: "朝のあいさつは 'Good morning.' です。'Good night.' は夜寝る前のあいさつです。",
    difficulty: 1,
  },
  {
    id: "english-grade2-2",
    subject: "english",
    grade: "grade2",
    unit: "あいさつ表現",
    prompt: "友達が帰る時のあいさつはどれですか。",
    choices: [
      { id: "a", label: "Hello." },
      { id: "b", label: "Thank you." },
      { id: "c", label: "Goodbye." },
    ],
    correctChoiceId: "c",
    explanation: "'Goodbye.' は別れる時のあいさつです。",
    difficulty: 1,
  },
  {
    id: "english-grade2-3",
    subject: "english",
    grade: "grade2",
    unit: "あいさつ表現",
    prompt: "「ありがとう」を英語で言うとどれですか。",
    choices: [
      { id: "a", label: "Thank you." },
      { id: "b", label: "Sorry." },
      { id: "c", label: "Please." },
    ],
    correctChoiceId: "a",
    explanation: "'Thank you.' は「ありがとう」という意味です。",
    difficulty: 1,
  },
  {
    id: "english-grade2-4",
    subject: "english",
    grade: "grade2",
    unit: "色の単語",
    prompt: "「あか(赤)」を英語で言うとどれですか。",
    choices: [
      { id: "a", label: "blue" },
      { id: "b", label: "red" },
      { id: "c", label: "green" },
    ],
    correctChoiceId: "b",
    explanation: "'red' は赤色を意味する英単語です。",
    difficulty: 1,
  },
  {
    id: "english-grade2-5",
    subject: "english",
    grade: "grade2",
    unit: "色の単語",
    prompt: "「あお(青)」を英語で言うとどれですか。",
    choices: [
      { id: "a", label: "blue" },
      { id: "b", label: "yellow" },
      { id: "c", label: "white" },
    ],
    correctChoiceId: "a",
    explanation: "'blue' は青色を意味する英単語です。",
    difficulty: 1,
  },
  {
    id: "english-grade2-6",
    subject: "english",
    grade: "grade2",
    unit: "色の単語",
    prompt: "「きいろ(黄色)」を英語で言うとどれですか。",
    choices: [
      { id: "a", label: "black" },
      { id: "b", label: "pink" },
      { id: "c", label: "yellow" },
    ],
    correctChoiceId: "c",
    explanation: "'yellow' は黄色を意味する英単語です。",
    difficulty: 1,
  },
  {
    id: "english-grade2-7",
    subject: "english",
    grade: "grade2",
    unit: "数字の単語",
    prompt: "「1」を英語で言うとどれですか。",
    choices: [
      { id: "a", label: "two" },
      { id: "b", label: "one" },
      { id: "c", label: "three" },
    ],
    correctChoiceId: "b",
    explanation: "'one' は数字の1を意味する英単語です。",
    difficulty: 1,
  },
  {
    id: "english-grade2-8",
    subject: "english",
    grade: "grade2",
    unit: "数字の単語",
    prompt: "「5」を英語で言うとどれですか。",
    choices: [
      { id: "a", label: "five" },
      { id: "b", label: "four" },
      { id: "c", label: "six" },
    ],
    correctChoiceId: "a",
    explanation: "'five' は数字の5を意味する英単語です。",
    difficulty: 1,
  },
  {
    id: "english-grade2-9",
    subject: "english",
    grade: "grade2",
    unit: "数字の単語",
    prompt: "「10」を英語で言うとどれですか。",
    choices: [
      { id: "a", label: "nine" },
      { id: "b", label: "eight" },
      { id: "c", label: "ten" },
    ],
    correctChoiceId: "c",
    explanation: "'ten' は数字の10を意味する英単語です。",
    difficulty: 2,
  },
  {
    id: "english-grade2-10",
    subject: "english",
    grade: "grade2",
    unit: "動物の単語",
    prompt: "この動物は何ですか。(ニャーニャーと鳴く)",
    choices: [
      { id: "a", label: "dog" },
      { id: "b", label: "cat" },
      { id: "c", label: "bird" },
    ],
    correctChoiceId: "b",
    explanation: "'cat' は猫を意味します。ニャーニャーと鳴くのは猫です。",
    difficulty: 1,
  },
  {
    id: "english-grade2-11",
    subject: "english",
    grade: "grade2",
    unit: "動物の単語",
    prompt: "この動物は何ですか。(ワンワンと鳴く)",
    choices: [
      { id: "a", label: "dog" },
      { id: "b", label: "pig" },
      { id: "c", label: "cat" },
    ],
    correctChoiceId: "a",
    explanation: "'dog' は犬を意味します。ワンワンと鳴くのは犬です。",
    difficulty: 1,
  },
  {
    id: "english-grade2-12",
    subject: "english",
    grade: "grade2",
    unit: "動物の単語",
    prompt: "この動物は何ですか。(耳が長く、ぴょんぴょん跳ねる)",
    choices: [
      { id: "a", label: "fish" },
      { id: "b", label: "horse" },
      { id: "c", label: "rabbit" },
    ],
    correctChoiceId: "c",
    explanation: "'rabbit' はうさぎを意味します。耳が長くぴょんぴょん跳ねます。",
    difficulty: 2,
  },
  {
    id: "english-grade2-13",
    subject: "english",
    grade: "grade2",
    unit: "食べ物の単語",
    prompt: "「りんご」を英語で言うとどれですか。",
    choices: [
      { id: "a", label: "orange" },
      { id: "b", label: "apple" },
      { id: "c", label: "grape" },
    ],
    correctChoiceId: "b",
    explanation: "'apple' はりんごを意味する英単語です。",
    difficulty: 1,
  },
  {
    id: "english-grade2-14",
    subject: "english",
    grade: "grade2",
    unit: "食べ物の単語",
    prompt: "「バナナ」を英語で言うとどれですか。",
    choices: [
      { id: "a", label: "banana" },
      { id: "b", label: "apple" },
      { id: "c", label: "melon" },
    ],
    correctChoiceId: "a",
    explanation: "'banana' はバナナを意味する英単語です。",
    difficulty: 1,
  },
  {
    id: "english-grade2-15",
    subject: "english",
    grade: "grade2",
    unit: "体の部位の単語",
    prompt: "「て(手)」を英語で言うとどれですか。",
    choices: [
      { id: "a", label: "foot" },
      { id: "b", label: "head" },
      { id: "c", label: "hand" },
    ],
    correctChoiceId: "c",
    explanation: "'hand' は手を意味する英単語です。",
    difficulty: 2,
  },

  // ==================== 英語/小5(外国語科 学習指導要領準拠) ====================
  {
    id: "english-grade5-1",
    subject: "english",
    grade: "grade5",
    unit: "自己紹介の表現",
    prompt: "自己紹介で名前を伝える時、正しい英文はどれですか。",
    choices: [
      { id: "a", label: "I name Ken." },
      { id: "b", label: "My name is Ken." },
      { id: "c", label: "Name my is Ken." },
    ],
    correctChoiceId: "b",
    explanation: "名前を伝える基本表現は 'My name is ~.' です。",
    difficulty: 1,
  },
  {
    id: "english-grade5-2",
    subject: "english",
    grade: "grade5",
    unit: "自己紹介の表現",
    prompt: "「私はミサキです。」を英語で表すとどれですか。",
    choices: [
      { id: "a", label: "I is Misaki." },
      { id: "b", label: "Am I Misaki." },
      { id: "c", label: "I am Misaki." },
    ],
    correctChoiceId: "c",
    explanation: "'I am ~.' で「私は~です」を表します。",
    difficulty: 1,
  },
  {
    id: "english-grade5-3",
    subject: "english",
    grade: "grade5",
    unit: "好き嫌いの表現",
    prompt: "「私はりんごが好きです。」を英語で表すとどれですか。",
    choices: [
      { id: "a", label: "I like apples." },
      { id: "b", label: "I likes apples." },
      { id: "c", label: "I don't like apples." },
    ],
    correctChoiceId: "a",
    explanation: "'I like ~.' で好きなものを伝えます。主語が I のとき動詞に s は付きません。",
    difficulty: 1,
  },
  {
    id: "english-grade5-4",
    subject: "english",
    grade: "grade5",
    unit: "好き嫌いの表現",
    prompt: "「私は納豆が好きではありません。」を英語で表すとどれですか。",
    choices: [
      { id: "a", label: "I like not natto." },
      { id: "b", label: "I don't like natto." },
      { id: "c", label: "I not like natto." },
    ],
    correctChoiceId: "b",
    explanation: "一般動詞の否定文は 'I don't like ~.' の形になります。",
    difficulty: 2,
  },
  {
    id: "english-grade5-5",
    subject: "english",
    grade: "grade5",
    unit: "曜日・時刻の表現",
    prompt: "「今日は何曜日ですか。」を英語で表すとどれですか。",
    choices: [
      { id: "a", label: "What time is it today?" },
      { id: "b", label: "What is today day?" },
      { id: "c", label: "What day is it today?" },
    ],
    correctChoiceId: "c",
    explanation: "曜日を尋ねる時は 'What day is it today?' と言います。",
    difficulty: 2,
  },
  {
    id: "english-grade5-6",
    subject: "english",
    grade: "grade5",
    unit: "曜日・時刻の表現",
    prompt: "「私は7時に起きます。」を英語で表すとどれですか。",
    choices: [
      { id: "a", label: "I get up at seven." },
      { id: "b", label: "I get up in seven." },
      { id: "c", label: "I get up on seven." },
    ],
    correctChoiceId: "a",
    explanation: "時刻を表す時は前置詞 'at' を使います。",
    difficulty: 2,
  },
  {
    id: "english-grade5-7",
    subject: "english",
    grade: "grade5",
    unit: "教科名の表現",
    prompt: "「理科」を英語で言うとどれですか。",
    choices: [
      { id: "a", label: "social studies" },
      { id: "b", label: "science" },
      { id: "c", label: "P.E." },
    ],
    correctChoiceId: "b",
    explanation: "'science' は理科を意味する英単語です。",
    difficulty: 1,
  },
  {
    id: "english-grade5-8",
    subject: "english",
    grade: "grade5",
    unit: "教科名の表現",
    prompt: "「好きな教科は算数です。」を英語で表すとどれですか。",
    choices: [
      { id: "a", label: "My favorite subject is music." },
      { id: "b", label: "My favorite subject is art." },
      { id: "c", label: "My favorite subject is math." },
    ],
    correctChoiceId: "c",
    explanation: "'math' は算数を意味する英単語です。",
    difficulty: 2,
  },
  {
    id: "english-grade5-9",
    subject: "english",
    grade: "grade5",
    unit: "日課の表現",
    prompt: "「私は6時に朝ごはんを食べます。」を英語で表すとどれですか。",
    choices: [
      { id: "a", label: "I eat breakfast at six." },
      { id: "b", label: "I eats breakfast at six." },
      { id: "c", label: "I ate breakfast six." },
    ],
    correctChoiceId: "a",
    explanation: "主語が I のとき、一般動詞は原形のまま使います。",
    difficulty: 2,
  },
  {
    id: "english-grade5-10",
    subject: "english",
    grade: "grade5",
    unit: "日課の表現",
    prompt: "「毎日学校へ行きますか。」を英語で表すとどれですか。",
    choices: [
      { id: "a", label: "Are you go to school every day?" },
      { id: "b", label: "Do you go to school every day?" },
      { id: "c", label: "Does you go to school every day?" },
    ],
    correctChoiceId: "b",
    explanation: "一般動詞の疑問文は、主語が you のとき 'Do you ~?' になります。",
    difficulty: 2,
  },
  {
    id: "english-grade5-11",
    subject: "english",
    grade: "grade5",
    unit: "できることの表現",
    prompt: "「私は泳ぐことができます。」を英語で表すとどれですか。",
    choices: [
      { id: "a", label: "I can swims." },
      { id: "b", label: "I swim can." },
      { id: "c", label: "I can swim." },
    ],
    correctChoiceId: "c",
    explanation: "'can' の後ろの動詞は原形のまま使います。",
    difficulty: 1,
  },
  {
    id: "english-grade5-12",
    subject: "english",
    grade: "grade5",
    unit: "できることの表現",
    prompt: "「私は自転車に乗れません。」を英語で表すとどれですか。",
    choices: [
      { id: "a", label: "I can't ride a bike." },
      { id: "b", label: "I not can ride a bike." },
      { id: "c", label: "I can ride not a bike." },
    ],
    correctChoiceId: "a",
    explanation: "can の否定形は 'can't (cannot)' で、動詞の前に置きます。",
    difficulty: 3,
  },
  {
    id: "english-grade5-13",
    subject: "english",
    grade: "grade5",
    unit: "道案内の表現",
    prompt: "「郵便局はどこですか。」を英語で表すとどれですか。",
    choices: [
      { id: "a", label: "Where the post office is?" },
      { id: "b", label: "Where is the post office?" },
      { id: "c", label: "What is the post office?" },
    ],
    correctChoiceId: "b",
    explanation: "場所を尋ねる時は 'Where is ~?' を使います。",
    difficulty: 3,
  },
  {
    id: "english-grade5-14",
    subject: "english",
    grade: "grade5",
    unit: "道案内の表現",
    prompt: "道を尋ねられて「まっすぐ行ってください。」と伝える時の英語はどれですか。",
    choices: [
      { id: "a", label: "Go straight." },
      { id: "b", label: "Turn left." },
      { id: "c", label: "Stop here." },
    ],
    correctChoiceId: "a",
    explanation: "'Go straight.' は「まっすぐ行く」という意味です。",
    difficulty: 1,
  },
  {
    id: "english-grade5-15",
    subject: "english",
    grade: "grade5",
    unit: "食べ物の表現",
    prompt: "「パン」を英語で言うとどれですか。",
    choices: [
      { id: "a", label: "rice" },
      { id: "b", label: "noodle" },
      { id: "c", label: "bread" },
    ],
    correctChoiceId: "c",
    explanation: "'bread' はパンを意味する英単語です。",
    difficulty: 1,
  },
  {
    id: "english-grade5-16",
    subject: "english",
    grade: "grade5",
    unit: "食べ物の表現",
    prompt: "「私は魚が好きではありません。」を英語で表すとどれですか。",
    choices: [
      { id: "a", label: "I don't like fish." },
      { id: "b", label: "I not like fish." },
      { id: "c", label: "I isn't like fish." },
    ],
    correctChoiceId: "a",
    explanation: "一般動詞の否定文は 'don't' を動詞の前に置きます。",
    difficulty: 2,
  },
  {
    id: "english-grade5-17",
    subject: "english",
    grade: "grade5",
    unit: "天気の表現",
    prompt: "「晴れ」を表す英単語はどれですか。",
    choices: [
      { id: "a", label: "rainy" },
      { id: "b", label: "sunny" },
      { id: "c", label: "cloudy" },
    ],
    correctChoiceId: "b",
    explanation: "'sunny' は晴れという意味の英単語です。",
    difficulty: 1,
  },
  {
    id: "english-grade5-18",
    subject: "english",
    grade: "grade5",
    unit: "天気の表現",
    prompt: "\"Is it sunny today?\" と聞かれて、晴れている時の正しい答えはどれですか。",
    choices: [
      { id: "a", label: "No, it isn't." },
      { id: "b", label: "Yes, it isn't." },
      { id: "c", label: "Yes, it is." },
    ],
    correctChoiceId: "c",
    explanation: "be動詞の疑問文に「そうです」と答える時は 'Yes, it is.' と言います。",
    difficulty: 3,
  },
  {
    id: "english-grade5-19",
    subject: "english",
    grade: "grade5",
    unit: "数字の表現",
    prompt: "「20」を英語で言うとどれですか。",
    choices: [
      { id: "a", label: "twenty" },
      { id: "b", label: "twelve" },
      { id: "c", label: "two" },
    ],
    correctChoiceId: "a",
    explanation: "'twenty' は20を意味する英単語です。",
    difficulty: 1,
  },
  {
    id: "english-grade5-20",
    subject: "english",
    grade: "grade5",
    unit: "数字の表現",
    prompt: "「15」を英語で言うとどれですか。",
    choices: [
      { id: "a", label: "fifty" },
      { id: "b", label: "fifteen" },
      { id: "c", label: "five" },
    ],
    correctChoiceId: "b",
    explanation: "'fifteen' は15を意味する英単語です。",
    difficulty: 1,
  },
  {
    id: "english-grade5-21",
    subject: "english",
    grade: "grade5",
    unit: "色の表現",
    prompt: "「緑」を表す英単語はどれですか。",
    choices: [
      { id: "a", label: "blue" },
      { id: "b", label: "purple" },
      { id: "c", label: "green" },
    ],
    correctChoiceId: "c",
    explanation: "'green' は緑色を意味する英単語です。",
    difficulty: 1,
  },
  {
    id: "english-grade5-22",
    subject: "english",
    grade: "grade5",
    unit: "色の表現",
    prompt: "英単語 \"orange\" が表す色は何色ですか。",
    choices: [
      { id: "a", label: "オレンジ色" },
      { id: "b", label: "紫色" },
      { id: "c", label: "緑色" },
    ],
    correctChoiceId: "a",
    explanation: "'orange' はオレンジ色を意味する英単語です。",
    difficulty: 1,
  },
  {
    id: "english-grade5-23",
    subject: "english",
    grade: "grade5",
    unit: "動物の表現",
    prompt: "「うさぎ」を英語で言うとどれですか。",
    choices: [
      { id: "a", label: "rat" },
      { id: "b", label: "rabbit" },
      { id: "c", label: "horse" },
    ],
    correctChoiceId: "b",
    explanation: "'rabbit' はうさぎを意味する英単語です。",
    difficulty: 1,
  },
  {
    id: "english-grade5-24",
    subject: "english",
    grade: "grade5",
    unit: "動物の表現",
    prompt: "「馬」を英語で言うとどれですか。",
    choices: [
      { id: "a", label: "horse" },
      { id: "b", label: "cow" },
      { id: "c", label: "sheep" },
    ],
    correctChoiceId: "a",
    explanation: "'horse' は馬を意味する英単語です。",
    difficulty: 1,
  },
  {
    id: "english-grade5-25",
    subject: "english",
    grade: "grade5",
    unit: "家族の表現",
    prompt: "「兄・弟」を表す英単語はどれですか。",
    choices: [
      { id: "a", label: "sister" },
      { id: "b", label: "mother" },
      { id: "c", label: "brother" },
    ],
    correctChoiceId: "c",
    explanation: "'brother' は男のきょうだい(兄・弟)を意味する英単語です。",
    difficulty: 1,
  },
  {
    id: "english-grade5-26",
    subject: "english",
    grade: "grade5",
    unit: "家族の表現",
    prompt: "「これは私の家族です。」を英語で表すとどれですか。",
    choices: [
      { id: "a", label: "This my family is." },
      { id: "b", label: "This is my family." },
      { id: "c", label: "This is family my." },
    ],
    correctChoiceId: "b",
    explanation: "'This is my family.' で「これは私の家族です」を表します。",
    difficulty: 2,
  },
];
