// client/src/game/content/questions/math.ts
//
// 算数コンテンツ(小2/小5)。学習指導要領準拠。
// 小2: 数の理解(位取り)/たし算・ひき算の筆算/かけ算(九九)/長さの単位/
//      かさの単位/時刻と時間/図形(三角形・四角形)/表とグラフ
// 小5: 小数のかけ算・わり算/分数のたし算・ひき算/約数・倍数/図形の面積/
//      合同な図形・多角形の内角・正多角形/単位量あたりの大きさ(速さ)/
//      割合・百分率・グラフ/平均
//
// 全問、correctChoiceId の計算結果は作成時に検算済み。
// 文章題の題材は買い物・自然観察・スポーツ・学校生活など平和的なものに限定している。

import type { ContentItem } from "@/game/types";

export const MATH_QUESTIONS: ContentItem[] = [
  // ==================== 算数/小2 ====================

  // --- 数の表し方(位取り) ---
  {
    id: "math-grade2-1",
    subject: "math",
    grade: "grade2",
    unit: "数の表し方(位取り)",
    prompt: "354という数の十の位の数字は何ですか。",
    choices: [
      { id: "a", label: "3" },
      { id: "b", label: "5" },
      { id: "c", label: "4" },
      { id: "d", label: "0" },
    ],
    correctChoiceId: "b",
    explanation: "354は百の位が3、十の位が5、一の位が4です。",
    difficulty: 1,
  },
  {
    id: "math-grade2-2",
    subject: "math",
    grade: "grade2",
    unit: "数の表し方(位取り)",
    prompt: "100を4こ、10を6こ、1を8こ あわせた数はいくつですか。",
    choices: [
      { id: "a", label: "468" },
      { id: "b", label: "486" },
      { id: "c", label: "648" },
      { id: "d", label: "368" },
    ],
    correctChoiceId: "a",
    explanation: "100が4こで400、10が6こで60、1が8こで8。あわせて468です。",
    difficulty: 2,
  },

  // --- たし算・ひき算の筆算 ---
  {
    id: "math-grade2-3",
    subject: "math",
    grade: "grade2",
    unit: "たし算の筆算",
    prompt: "48 + 27 を筆算で計算しましょう。答えはいくつですか。",
    choices: [
      { id: "a", label: "75" },
      { id: "b", label: "65" },
      { id: "c", label: "85" },
      { id: "d", label: "615" },
    ],
    correctChoiceId: "a",
    explanation:
      "一の位: 8+7=15なので5を書いて1くり上げる。十の位: 4+2+1(くり上がり)=7。答えは75です。",
    difficulty: 1,
  },
  {
    id: "math-grade2-4",
    subject: "math",
    grade: "grade2",
    unit: "たし算の筆算",
    prompt: "花だんに赤い花が37本、白い花が26本さいています。花は全部で何本さいていますか。",
    choices: [
      { id: "a", label: "63本" },
      { id: "b", label: "53本" },
      { id: "c", label: "613本" },
      { id: "d", label: "11本" },
    ],
    correctChoiceId: "a",
    explanation:
      "37+26を計算します。一の位7+6=13で3を書いて1くり上げ、十の位3+2+1=6。答えは63本です。",
    difficulty: 2,
  },
  {
    id: "math-grade2-5",
    subject: "math",
    grade: "grade2",
    unit: "ひき算の筆算",
    prompt: "52 - 27 を筆算で計算しましょう。答えはいくつですか。",
    choices: [
      { id: "a", label: "25" },
      { id: "b", label: "35" },
      { id: "c", label: "75" },
      { id: "d", label: "20" },
    ],
    correctChoiceId: "a",
    explanation:
      "一の位2-7はできないので十の位から1借りて12-7=5。十の位は借りた分を引いて4-2=2。答えは25です。",
    difficulty: 2,
  },
  {
    id: "math-grade2-6",
    subject: "math",
    grade: "grade2",
    unit: "ひき算の筆算",
    prompt: "はじめにビー玉を61こ持っていました。友だちに34こあげました。残りは何こですか。",
    choices: [
      { id: "a", label: "27こ" },
      { id: "b", label: "37こ" },
      { id: "c", label: "33こ" },
      { id: "d", label: "95こ" },
    ],
    correctChoiceId: "a",
    explanation:
      "61-34を計算します。一の位1-4はできないので十の位から借りて11-4=7。十の位は借りた分を引いて5-3=2。答えは27こです。",
    difficulty: 2,
  },

  // --- かけ算(九九、乗法の意味) ---
  {
    id: "math-grade2-7",
    subject: "math",
    grade: "grade2",
    unit: "かけ算(九九)",
    prompt: "7 × 8 の答えはいくつですか。",
    choices: [
      { id: "a", label: "54" },
      { id: "b", label: "56" },
      { id: "c", label: "63" },
      { id: "d", label: "48" },
    ],
    correctChoiceId: "b",
    explanation: "7のだんの九九で、7×8=56です。",
    difficulty: 1,
  },
  {
    id: "math-grade2-8",
    subject: "math",
    grade: "grade2",
    unit: "かけ算(九九)",
    prompt: "6 × 9 の答えはいくつですか。",
    choices: [
      { id: "a", label: "56" },
      { id: "b", label: "63" },
      { id: "c", label: "54" },
      { id: "d", label: "45" },
    ],
    correctChoiceId: "c",
    explanation: "6のだんの九九で、6×9=54です。",
    difficulty: 1,
  },
  {
    id: "math-grade2-9",
    subject: "math",
    grade: "grade2",
    unit: "かけ算(九九の意味)",
    prompt: "1はこにドーナツが5こ入っています。4はこ買うと、ドーナツは全部で何こになりますか。",
    choices: [
      { id: "a", label: "20こ" },
      { id: "b", label: "9こ" },
      { id: "c", label: "25こ" },
      { id: "d", label: "15こ" },
    ],
    correctChoiceId: "a",
    explanation: "1はこ5こが4はこ分なので、5×4=20こです。",
    difficulty: 2,
  },
  {
    id: "math-grade2-10",
    subject: "math",
    grade: "grade2",
    unit: "かけ算(九九の意味)",
    prompt: "1つのふくろにあめが3こ入っています。7つのふくろでは、あめは何こになりますか。",
    choices: [
      { id: "a", label: "21こ" },
      { id: "b", label: "10こ" },
      { id: "c", label: "18こ" },
      { id: "d", label: "24こ" },
    ],
    correctChoiceId: "a",
    explanation: "3こ入りのふくろが7つ分なので、3×7=21こです。",
    difficulty: 2,
  },

  // --- 長さの単位(mm, cm, m) ---
  {
    id: "math-grade2-11",
    subject: "math",
    grade: "grade2",
    unit: "長さの単位",
    prompt: "1cmは何mmですか。",
    choices: [
      { id: "a", label: "10mm" },
      { id: "b", label: "1mm" },
      { id: "c", label: "100mm" },
      { id: "d", label: "5mm" },
    ],
    correctChoiceId: "a",
    explanation: "1cm=10mmです。",
    difficulty: 1,
  },
  {
    id: "math-grade2-12",
    subject: "math",
    grade: "grade2",
    unit: "長さの単位",
    prompt: "えんぴつの長さをはかったら14cmでした。これは何mmですか。",
    choices: [
      { id: "a", label: "140mm" },
      { id: "b", label: "14mm" },
      { id: "c", label: "104mm" },
      { id: "d", label: "1400mm" },
    ],
    correctChoiceId: "a",
    explanation: "1cm=10mmなので、14cm=14×10=140mmです。",
    difficulty: 2,
  },
  {
    id: "math-grade2-13",
    subject: "math",
    grade: "grade2",
    unit: "長さの単位",
    prompt: "3mは何cmですか。",
    choices: [
      { id: "a", label: "30cm" },
      { id: "b", label: "300cm" },
      { id: "c", label: "3cm" },
      { id: "d", label: "3000cm" },
    ],
    correctChoiceId: "b",
    explanation: "1m=100cmなので、3m=3×100=300cmです。",
    difficulty: 2,
  },

  // --- かさの単位(dL, L, mL) ---
  {
    id: "math-grade2-14",
    subject: "math",
    grade: "grade2",
    unit: "かさの単位",
    prompt: "1Lは何dLですか。",
    choices: [
      { id: "a", label: "10dL" },
      { id: "b", label: "100dL" },
      { id: "c", label: "1dL" },
      { id: "d", label: "1000dL" },
    ],
    correctChoiceId: "a",
    explanation: "1L=10dLです。",
    difficulty: 1,
  },
  {
    id: "math-grade2-15",
    subject: "math",
    grade: "grade2",
    unit: "かさの単位",
    prompt: "水とうに水が2L入っています。コップに3dL使いました。残りは何dLですか。",
    choices: [
      { id: "a", label: "17dL" },
      { id: "b", label: "7dL" },
      { id: "c", label: "23dL" },
      { id: "d", label: "18dL" },
    ],
    correctChoiceId: "a",
    explanation: "2L=20dLです。20dL-3dL=17dLになります。",
    difficulty: 3,
  },
  {
    id: "math-grade2-16",
    subject: "math",
    grade: "grade2",
    unit: "かさの単位",
    prompt: "500mLの牛乳パックが2本あります。あわせて何mLですか。",
    choices: [
      { id: "a", label: "1000mL" },
      { id: "b", label: "250mL" },
      { id: "c", label: "700mL" },
      { id: "d", label: "1050mL" },
    ],
    correctChoiceId: "a",
    explanation: "500mL×2=1000mL(=1L)です。",
    difficulty: 2,
  },

  // --- 時刻と時間 ---
  {
    id: "math-grade2-17",
    subject: "math",
    grade: "grade2",
    unit: "時刻と時間",
    prompt: "時計が「3時45分」を指しています。この15分後は何時何分ですか。",
    choices: [
      { id: "a", label: "4時0分" },
      { id: "b", label: "3時60分" },
      { id: "c", label: "4時15分" },
      { id: "d", label: "3時50分" },
    ],
    correctChoiceId: "a",
    explanation: "3時45分の15分後は、ちょうど4時になります。",
    difficulty: 2,
  },
  {
    id: "math-grade2-18",
    subject: "math",
    grade: "grade2",
    unit: "時刻と時間",
    prompt: "午後2時は、午前0時から数える24時間の表し方で何時ですか。",
    choices: [
      { id: "a", label: "12時" },
      { id: "b", label: "14時" },
      { id: "c", label: "2時" },
      { id: "d", label: "20時" },
    ],
    correctChoiceId: "b",
    explanation: "午後2時は正午(12時)から2時間後なので、12+2=14時です。",
    difficulty: 2,
  },
  {
    id: "math-grade2-19",
    subject: "math",
    grade: "grade2",
    unit: "時刻と時間",
    prompt: "サッカーの練習は午後3時に始まり、午後4時20分に終わりました。練習時間は何分間ですか。",
    choices: [
      { id: "a", label: "80分" },
      { id: "b", label: "120分" },
      { id: "c", label: "20分" },
      { id: "d", label: "140分" },
    ],
    correctChoiceId: "a",
    explanation: "3時から4時までが60分、4時から4時20分までが20分。あわせて60+20=80分間です。",
    difficulty: 3,
  },

  // --- 図形(三角形・四角形の弁別、辺・頂点) ---
  {
    id: "math-grade2-20",
    subject: "math",
    grade: "grade2",
    unit: "図形(三角形・四角形)",
    prompt: "3本の直線でかこまれた形を何といいますか。",
    choices: [
      { id: "a", label: "三角形" },
      { id: "b", label: "四角形" },
      { id: "c", label: "円" },
      { id: "d", label: "五角形" },
    ],
    correctChoiceId: "a",
    explanation: "3本の直線でかこまれた形を三角形といいます。",
    difficulty: 1,
  },
  {
    id: "math-grade2-21",
    subject: "math",
    grade: "grade2",
    unit: "図形(三角形・四角形)",
    prompt: "四角形には、頂点(かど)がいくつありますか。",
    choices: [
      { id: "a", label: "3つ" },
      { id: "b", label: "4つ" },
      { id: "c", label: "5つ" },
      { id: "d", label: "6つ" },
    ],
    correctChoiceId: "b",
    explanation: "四角形は辺が4本、頂点(かど)も4つあります。",
    difficulty: 1,
  },

  // --- 表とグラフの読み取り ---
  {
    id: "math-grade2-22",
    subject: "math",
    grade: "grade2",
    unit: "表とグラフ",
    prompt:
      "クラスで好きな果物を調べたら、りんご8人、みかん5人、ぶどう3人、バナナ4人でした。いちばん多く選ばれた果物はどれですか。",
    choices: [
      { id: "a", label: "りんご" },
      { id: "b", label: "みかん" },
      { id: "c", label: "ぶどう" },
      { id: "d", label: "バナナ" },
    ],
    correctChoiceId: "a",
    explanation: "表の中でりんごが8人といちばん多いです。",
    difficulty: 1,
  },
  {
    id: "math-grade2-23",
    subject: "math",
    grade: "grade2",
    unit: "表とグラフ",
    prompt:
      "上の果物調べ(りんご8人、みかん5人、ぶどう3人、バナナ4人)で、みかんとぶどうを選んだ人をあわせると何人ですか。",
    choices: [
      { id: "a", label: "8人" },
      { id: "b", label: "9人" },
      { id: "c", label: "7人" },
      { id: "d", label: "12人" },
    ],
    correctChoiceId: "a",
    explanation: "みかん5人とぶどう3人をあわせて、5+3=8人です。",
    difficulty: 2,
  },

  // ==================== 算数/小5 ====================

  // --- 小数のかけ算・わり算 ---
  {
    id: "math-grade5-1",
    subject: "math",
    grade: "grade5",
    unit: "小数のかけ算",
    prompt: "2.3 × 4 の計算をしてください。答えはいくつですか。",
    choices: [
      { id: "a", label: "9.2" },
      { id: "b", label: "8.2" },
      { id: "c", label: "92" },
      { id: "d", label: "6.3" },
    ],
    correctChoiceId: "a",
    explanation: "2.3×4=9.2です。小数点の位置に注意して計算します。",
    difficulty: 1,
  },
  {
    id: "math-grade5-2",
    subject: "math",
    grade: "grade5",
    unit: "小数のかけ算",
    prompt: "1mの重さが0.6kgのリボンがあります。3.5m分の重さは何kgですか。",
    choices: [
      { id: "a", label: "2.1kg" },
      { id: "b", label: "1.5kg" },
      { id: "c", label: "21kg" },
      { id: "d", label: "2.4kg" },
    ],
    correctChoiceId: "a",
    explanation: "1mあたりの重さ×長さで求めます。0.6×3.5=2.1kgです。",
    difficulty: 2,
  },
  {
    id: "math-grade5-3",
    subject: "math",
    grade: "grade5",
    unit: "小数のわり算",
    prompt: "7.2 ÷ 3 の計算をしてください。答えはいくつですか。",
    choices: [
      { id: "a", label: "2.4" },
      { id: "b", label: "2.04" },
      { id: "c", label: "24" },
      { id: "d", label: "3.4" },
    ],
    correctChoiceId: "a",
    explanation: "7.2÷3=2.4です。",
    difficulty: 1,
  },
  {
    id: "math-grade5-4",
    subject: "math",
    grade: "grade5",
    unit: "小数のわり算",
    prompt: "5.6Lのジュースを、4人で同じ量ずつ分けます。1人分は何Lですか。",
    choices: [
      { id: "a", label: "1.4L" },
      { id: "b", label: "1.04L" },
      { id: "c", label: "14L" },
      { id: "d", label: "2.4L" },
    ],
    correctChoiceId: "a",
    explanation: "5.6÷4=1.4Lです。",
    difficulty: 2,
  },

  // --- 分数のたし算・ひき算(異分母、通分) ---
  {
    id: "math-grade5-5",
    subject: "math",
    grade: "grade5",
    unit: "分数のたし算",
    prompt: "1/2 + 1/3 の計算をしてください。答えはいくつですか。",
    choices: [
      { id: "a", label: "5/6" },
      { id: "b", label: "2/5" },
      { id: "c", label: "1/6" },
      { id: "d", label: "5/5" },
    ],
    correctChoiceId: "a",
    explanation: "分母を6にそろえて通分します。3/6+2/6=5/6です。",
    difficulty: 2,
  },
  {
    id: "math-grade5-6",
    subject: "math",
    grade: "grade5",
    unit: "分数のひき算",
    prompt: "3/4 - 1/6 の計算をしてください。答えはいくつですか。",
    choices: [
      { id: "a", label: "7/12" },
      { id: "b", label: "5/12" },
      { id: "c", label: "7/24" },
      { id: "d", label: "11/12" },
    ],
    correctChoiceId: "a",
    explanation: "分母を12にそろえて通分します。9/12-2/12=7/12です。",
    difficulty: 2,
  },
  {
    id: "math-grade5-7",
    subject: "math",
    grade: "grade5",
    unit: "分数のたし算",
    prompt: "2/5 + 3/10 の計算をしてください。答えはいくつですか。",
    choices: [
      { id: "a", label: "7/10" },
      { id: "b", label: "5/15" },
      { id: "c", label: "1/2" },
      { id: "d", label: "7/15" },
    ],
    correctChoiceId: "a",
    explanation: "2/5を10を分母にそろえて4/10にします。4/10+3/10=7/10です。",
    difficulty: 2,
  },

  // --- 約数・倍数、公約数・公倍数 ---
  {
    id: "math-grade5-8",
    subject: "math",
    grade: "grade5",
    unit: "約数",
    prompt: "次のうち、12の約数でないものはどれですか。",
    choices: [
      { id: "a", label: "3" },
      { id: "b", label: "4" },
      { id: "c", label: "5" },
      { id: "d", label: "6" },
    ],
    correctChoiceId: "c",
    explanation: "12は1,2,3,4,6,12で割り切れます。5では割り切れないので約数ではありません。",
    difficulty: 2,
  },
  {
    id: "math-grade5-9",
    subject: "math",
    grade: "grade5",
    unit: "公約数",
    prompt: "8と12の最大公約数(公約数のうちいちばん大きい数)はいくつですか。",
    choices: [
      { id: "a", label: "2" },
      { id: "b", label: "4" },
      { id: "c", label: "6" },
      { id: "d", label: "24" },
    ],
    correctChoiceId: "b",
    explanation: "8の約数は1,2,4,8。12の約数は1,2,3,4,6,12。共通する最大の数は4です。",
    difficulty: 2,
  },
  {
    id: "math-grade5-10",
    subject: "math",
    grade: "grade5",
    unit: "公倍数",
    prompt: "4と6の最小公倍数(公倍数のうちいちばん小さい数)はいくつですか。",
    choices: [
      { id: "a", label: "10" },
      { id: "b", label: "12" },
      { id: "c", label: "24" },
      { id: "d", label: "2" },
    ],
    correctChoiceId: "b",
    explanation: "4の倍数は4,8,12…。6の倍数は6,12…。最初に共通する数は12です。",
    difficulty: 2,
  },

  // --- 図形の面積(平行四辺形・三角形・台形・ひし形) ---
  {
    id: "math-grade5-11",
    subject: "math",
    grade: "grade5",
    unit: "図形の面積(平行四辺形)",
    prompt: "底辺7cm、高さ4cmの平行四辺形の面積は何平方センチメートルですか。",
    choices: [
      { id: "a", label: "28cm²" },
      { id: "b", label: "22cm²" },
      { id: "c", label: "14cm²" },
      { id: "d", label: "56cm²" },
    ],
    correctChoiceId: "a",
    explanation: "平行四辺形の面積=底辺×高さ=7×4=28cm²です。",
    difficulty: 1,
  },
  {
    id: "math-grade5-12",
    subject: "math",
    grade: "grade5",
    unit: "図形の面積(三角形)",
    prompt: "底辺10cm、高さ6cmの三角形の面積は何平方センチメートルですか。",
    choices: [
      { id: "a", label: "60cm²" },
      { id: "b", label: "30cm²" },
      { id: "c", label: "16cm²" },
      { id: "d", label: "20cm²" },
    ],
    correctChoiceId: "b",
    explanation: "三角形の面積=底辺×高さ÷2=10×6÷2=30cm²です。",
    difficulty: 2,
  },
  {
    id: "math-grade5-13",
    subject: "math",
    grade: "grade5",
    unit: "図形の面積(台形)",
    prompt: "上底4cm、下底8cm、高さ5cmの台形の面積は何平方センチメートルですか。",
    choices: [
      { id: "a", label: "30cm²" },
      { id: "b", label: "60cm²" },
      { id: "c", label: "20cm²" },
      { id: "d", label: "40cm²" },
    ],
    correctChoiceId: "a",
    explanation: "台形の面積=(上底+下底)×高さ÷2=(4+8)×5÷2=30cm²です。",
    difficulty: 3,
  },
  {
    id: "math-grade5-14",
    subject: "math",
    grade: "grade5",
    unit: "図形の面積(ひし形)",
    prompt: "対角線の長さが6cmと8cmのひし形の面積は何平方センチメートルですか。",
    choices: [
      { id: "a", label: "48cm²" },
      { id: "b", label: "24cm²" },
      { id: "c", label: "14cm²" },
      { id: "d", label: "28cm²" },
    ],
    correctChoiceId: "b",
    explanation: "ひし形の面積=対角線×対角線÷2=6×8÷2=24cm²です。",
    difficulty: 2,
  },

  // --- 合同な図形、多角形の内角の和、正多角形 ---
  {
    id: "math-grade5-15",
    subject: "math",
    grade: "grade5",
    unit: "合同な図形",
    prompt: "2つの図形の形と大きさが同じで、ぴったり重ね合わせられるとき、この2つの図形の関係を何といいますか。",
    choices: [
      { id: "a", label: "相似" },
      { id: "b", label: "合同" },
      { id: "c", label: "対称" },
      { id: "d", label: "平行" },
    ],
    correctChoiceId: "b",
    explanation: "形と大きさが同じでぴったり重なる図形を「合同」な図形といいます。",
    difficulty: 1,
  },
  {
    id: "math-grade5-16",
    subject: "math",
    grade: "grade5",
    unit: "多角形の内角の和",
    prompt: "四角形の内角の和は何度ですか。",
    choices: [
      { id: "a", label: "180°" },
      { id: "b", label: "360°" },
      { id: "c", label: "270°" },
      { id: "d", label: "540°" },
    ],
    correctChoiceId: "b",
    explanation: "四角形は対角線で三角形2つに分けられるので、180°×2=360°です。",
    difficulty: 2,
  },
  {
    id: "math-grade5-17",
    subject: "math",
    grade: "grade5",
    unit: "正多角形",
    prompt: "正六角形の1つの内角の大きさは何度ですか。",
    choices: [
      { id: "a", label: "90°" },
      { id: "b", label: "100°" },
      { id: "c", label: "120°" },
      { id: "d", label: "150°" },
    ],
    correctChoiceId: "c",
    explanation: "六角形の内角の和は(6-2)×180=720°。正六角形は6つの角がすべて等しいので、720÷6=120°です。",
    difficulty: 3,
  },

  // --- 単位量あたりの大きさ(速さを含む) ---
  {
    id: "math-grade5-18",
    subject: "math",
    grade: "grade5",
    unit: "単位量あたりの大きさ",
    prompt:
      "A公園は面積12㎡で6人が遊んでいます。B公園は面積20㎡で8人が遊んでいます。1人あたりの面積が広いのはどちらの公園ですか。",
    choices: [
      { id: "a", label: "A公園" },
      { id: "b", label: "B公園" },
      { id: "c", label: "どちらも同じ" },
      { id: "d", label: "わからない" },
    ],
    correctChoiceId: "b",
    explanation: "A公園は1人あたり12÷6=2㎡、B公園は20÷8=2.5㎡。B公園のほうが1人あたりの面積が広いです。",
    difficulty: 3,
  },
  {
    id: "math-grade5-19",
    subject: "math",
    grade: "grade5",
    unit: "速さ",
    prompt: "自動車が180kmの道のりを3時間で走りました。この自動車の速さは時速何kmですか。",
    choices: [
      { id: "a", label: "時速60km" },
      { id: "b", label: "時速540km" },
      { id: "c", label: "時速30km" },
      { id: "d", label: "時速90km" },
    ],
    correctChoiceId: "a",
    explanation: "速さ=道のり÷時間=180÷3=時速60kmです。",
    difficulty: 2,
  },
  {
    id: "math-grade5-20",
    subject: "math",
    grade: "grade5",
    unit: "速さ",
    prompt: "時速4kmで歩く人が、2時間で歩く道のりは何kmですか。",
    choices: [
      { id: "a", label: "8km" },
      { id: "b", label: "2km" },
      { id: "c", label: "6km" },
      { id: "d", label: "16km" },
    ],
    correctChoiceId: "a",
    explanation: "道のり=速さ×時間=4×2=8kmです。",
    difficulty: 2,
  },

  // --- 割合・百分率、円グラフ・帯グラフの読み取り ---
  {
    id: "math-grade5-21",
    subject: "math",
    grade: "grade5",
    unit: "割合・百分率",
    prompt: "定員40人のバスに32人乗っています。乗車率(割合)は何パーセントですか。",
    choices: [
      { id: "a", label: "80%" },
      { id: "b", label: "8%" },
      { id: "c", label: "32%" },
      { id: "d", label: "125%" },
    ],
    correctChoiceId: "a",
    explanation: "32÷40=0.8=80%です。",
    difficulty: 2,
  },
  {
    id: "math-grade5-22",
    subject: "math",
    grade: "grade5",
    unit: "円グラフの読み取り",
    prompt: "円グラフで、りんごの部分が全体の25%を占めています。りんごの部分は円の何分の1にあたりますか。",
    choices: [
      { id: "a", label: "4分の1" },
      { id: "b", label: "5分の1" },
      { id: "c", label: "2分の1" },
      { id: "d", label: "10分の1" },
    ],
    correctChoiceId: "a",
    explanation: "25%は100%の4分の1にあたるので、円の4分の1です。",
    difficulty: 2,
  },
  {
    id: "math-grade5-23",
    subject: "math",
    grade: "grade5",
    unit: "帯グラフの読み取り",
    prompt:
      "あるクラスの好きなスポーツを帯グラフに表したところ、サッカーが40%、野球が30%、バスケットボールが20%、その他が10%でした。サッカーと野球をあわせると全体の何パーセントですか。",
    choices: [
      { id: "a", label: "70%" },
      { id: "b", label: "60%" },
      { id: "c", label: "50%" },
      { id: "d", label: "90%" },
    ],
    correctChoiceId: "a",
    explanation: "サッカー40%と野球30%をあわせて、40+30=70%です。",
    difficulty: 2,
  },

  // --- 平均 ---
  {
    id: "math-grade5-24",
    subject: "math",
    grade: "grade5",
    unit: "平均",
    prompt: "3回のテストの点数が80点、90点、70点でした。平均点は何点ですか。",
    choices: [
      { id: "a", label: "80点" },
      { id: "b", label: "75点" },
      { id: "c", label: "240点" },
      { id: "d", label: "85点" },
    ],
    correctChoiceId: "a",
    explanation: "80+90+70=240。240÷3=80点が平均です。",
    difficulty: 2,
  },
  {
    id: "math-grade5-25",
    subject: "math",
    grade: "grade5",
    unit: "平均",
    prompt: "5日間の最高気温が、28℃、30℃、26℃、32℃、29℃でした。この5日間の平均気温は何℃ですか。",
    choices: [
      { id: "a", label: "29℃" },
      { id: "b", label: "30℃" },
      { id: "c", label: "145℃" },
      { id: "d", label: "28℃" },
    ],
    correctChoiceId: "a",
    explanation: "28+30+26+32+29=145。145÷5=29℃が平均です。",
    difficulty: 3,
  },
];
